version: '3.8'

services:
  panda-php:
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    container_name: panda-php
    restart: unless-stopped
    env_file: ./src/.env
    volumes:
      - ./src:/var/www/html
    networks:
      - panda-network

  panda-nginx:
    image: nginx:alpine
    container_name: panda-nginx
    restart: unless-stopped
    ports:
      - "8080:80"  # Expose on port 8080
      - "5173:5173"
    volumes:
      - ./src:/var/www/html
      - ./nginx/panda.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - panda-php
    networks:
      - panda-network

networks:
  panda-network:
    driver: bridge

